### ISSUE TITLE
Add expected delivery time

### ISSUE THREAD

**Issue by Carlozzz92** [peternijssen/python-jumbo-api#4]
Hello,

Is it possible to add the expected delivery time?
When the delivery is processing, after a while the Jumbo app will give you an expected delivery time. The time will still be: '13:00 - 16:00', but the app will have an expected time (see picture below). I would like to also use this time.

![temp](https://user-images.githubusercontent.com/64526157/95208124-fdfdae00-07e8-11eb-8691-23930a93ed3c.jpeg)

**Comment by peternijssen** [comment]
Nice! Didn't notice it. Guess it's something new. Will definitely add it soon.

Thanks for reporting!

**Comment by peternijssen** [comment]
@Carlozzz92 I am currently awaiting my delivery, but I don't get such a specific time like you. It still mentions the time slot I've selected back then.

Any particular place it's located? Maybe it's only for certain cities :(

**Comment by Carlozzz92** [comment]
@peternijssen I can see the messages in "mijn inbox" in the jumbo app, my phone also gets the message on the screen when the jumbo app is closed.
![Mijn inbox](https://user-images.githubusercontent.com/64526157/95984201-2148de80-0e23-11eb-908e-a9125e27939e.jpeg)
![Meldingen](https://user-images.githubusercontent.com/64526157/95984208-23ab3880-0e23-11eb-94fb-488febd36e52.jpeg)

**Comment by peternijssen** [comment]
I don't have such a message unfortunately :(
But seems like it's the latest message of the inbox, so I could pull that message in and display it in lovelace card. Converting it to a date is probably harder.

**Comment by peternijssen** [comment]
I had a look and found out that I can't pull in the messages, as they are not part of the Jumbo API but part of a service they are using; https://notificare.com/. Therefor I am unable to retrieve the message and display it within HA.

Closing the issue, unfortunately.
